version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: sanjivani
      POSTGRES_PASSWORD: sanjivani_dev_pw
      POSTGRES_DB: sanjivani_codearena
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
